/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RPCproxy_thrift_file_CONSTANTS_H
#define RPCproxy_thrift_file_CONSTANTS_H

#include "RPCproxy_thrift_file_types.h"

namespace Test {

class RPCproxy_thrift_fileConstants {
 public:
  RPCproxy_thrift_fileConstants();

};

extern const RPCproxy_thrift_fileConstants g_RPCproxy_thrift_file_constants;

} // namespace

#endif
