/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RPCproxy_thrift_file_constants.h"

namespace Test {

const RPCproxy_thrift_fileConstants g_RPCproxy_thrift_file_constants;

RPCproxy_thrift_fileConstants::RPCproxy_thrift_fileConstants() {
}

} // namespace

