// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RPCproxy.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::Test;

class RPCproxyHandler : virtual public RPCproxyIf {
 public:
  RPCproxyHandler() {
    // Your initialization goes here
  }

  void ping(std::string& _return, const std::string& URL) {
    // Your implementation goes here
    printf("ping\n");
  }

  int32_t miss_count() {
    // Your implementation goes here
    printf("miss_count\n");
  }

  int32_t byte_count() {
    // Your implementation goes here
    printf("byte_count\n");
  }

  void kill_server() {
    // Your implementation goes here
    printf("kill_server\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<RPCproxyHandler> handler(new RPCproxyHandler());
  shared_ptr<TProcessor> processor(new RPCproxyProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

